
Logging:
  LogLevel:
    Default: "Information"
    Microsoft.AspNetCore: "Warning"

# Enter your info.
# CosmosDB:
#   Endpoint: "your_cosmosdb_endpoint_uri"
#   Key: "your_cosmosdb_authorization_key"
#   DatabaseName: "your_cosmosdb_database_name"

AllowedHosts: "*"